version: '3'
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - host
    environment:
      - MONGO_INITDB_DATABASE=Library
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass

  app:
    build: .
    command: python -u app.py
    ports: 
      - 5000:5000
    volumes:
      - .:/app
    links:
      - mongo
    networks:
      - host
networks:
    host: